version: '3.9'
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tyba}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    restart: always

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
